// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnCFg4bMfMJxLW3sFrWnR7K83qVZWu-6E',
    appId: '1:292647003953:web:79be119dac1269f552b210',
    messagingSenderId: '292647003953',
    projectId: 'bitirme-projesi-23',
    authDomain: 'bitirme-projesi-23.firebaseapp.com',
    databaseURL: 'https://bitirme-projesi-23-default-rtdb.firebaseio.com',
    storageBucket: 'bitirme-projesi-23.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtvmTFxlCi8NlEBXoy8EShDnJ7bgH71Js',
    appId: '1:292647003953:android:5f0541eea31e927052b210',
    messagingSenderId: '292647003953',
    projectId: 'bitirme-projesi-23',
    databaseURL: 'https://bitirme-projesi-23-default-rtdb.firebaseio.com',
    storageBucket: 'bitirme-projesi-23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIt3VaHl4mJZOSY6C3TuRBuwBQOpcGgD4',
    appId: '1:292647003953:ios:331d115b8134713252b210',
    messagingSenderId: '292647003953',
    projectId: 'bitirme-projesi-23',
    databaseURL: 'https://bitirme-projesi-23-default-rtdb.firebaseio.com',
    storageBucket: 'bitirme-projesi-23.appspot.com',
    iosClientId: '292647003953-m1tn6qm0fair58dev1jk70ci6gqglvq0.apps.googleusercontent.com',
    iosBundleId: 'com.example.bitirmeProjesi23',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIt3VaHl4mJZOSY6C3TuRBuwBQOpcGgD4',
    appId: '1:292647003953:ios:331d115b8134713252b210',
    messagingSenderId: '292647003953',
    projectId: 'bitirme-projesi-23',
    databaseURL: 'https://bitirme-projesi-23-default-rtdb.firebaseio.com',
    storageBucket: 'bitirme-projesi-23.appspot.com',
    iosClientId: '292647003953-m1tn6qm0fair58dev1jk70ci6gqglvq0.apps.googleusercontent.com',
    iosBundleId: 'com.example.bitirmeProjesi23',
  );
}
